language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != '<%= properties.projectName %>' ]; then cd .. && eval "mv $currentfolder <%= properties.projectName %>" && cd <%= properties.projectName %>; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
