language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'ProiectAppWeb' ]; then cd .. && eval "mv $currentfolder ProiectAppWeb" && cd ProiectAppWeb; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
